FROM nginx:latest

ENV BACKEND_URL=https://www.google.com
ENV DOLLARFIX=$

RUN apt update && apt upgrade -y && apt install openssl -y 

COPY default.template /etc/nginx/conf.d/

RUN mkdir /ssl
COPY open_ssl.conf /ssl
WORKDIR /ssl
RUN openssl req -x509 -nodes -days 1024 -newkey rsa:2048 -keyout /etc/ssl/nginx-cert.key -out /etc/ssl/nginx-cert.crt -config open_ssl.conf -extensions 'v3_req'
RUN envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf 
